### ISSUE TITLE
Additional Command Words for `target nearest <type> material trader`

### ISSUE THREAD

**Issue by F3Speech** [alterNERDtive/VoiceAttack-profiles#55]
[whats;what is] left to [map;be mapped] - Could you add **find** to the initial command [whats;what is;**find**] nearest [encoded;manufactured;raw] material trader

**Comment by alterNERDtive** [comment]
It’s actually `target nearest <type> material trader` but sure, I can add `find` to that.

I’ve avoided doing that in general since more commands will at some point ≙ slower reactions of VoiceAttack; but after seeing the amount of commands in e.g. HCS packs I’m kind of less concerned, and I can see how it could be useful to do some more variations.

**Comment by alterNERDtive** [comment]
Also relevant for `target nearest [guardian;human] tech broker` and `target nearest [interstellar factor;mission system;scoopable star]`.
