### ISSUE TITLE
Manually edit auto honk all systems to enable

### ISSUE THREAD

**Issue by suryakumaran11** [alterNERDtive/VoiceAttack-profiles#92]
For some reason .. this keyword is not recognized by voice attack for me . Can anyone help me where to set these toggle manually in the voice attack to enable ? @alterNERDtive 

road to riches: Announce bodies worth scanning if you are looking for some starting cash on the Road to Riches. Default: false  

I use this aswell .. Need to enable it to true

How i have my discovery scanner in trigger 2 of the A firegroup it is not working aswell

**Comment by alterNERDtive** [comment]
Did you use the proper commands outlined in https://alternerdtive.github.io/VoiceAttack-profiles/configuration/general/#settings?

Have you included the base profile correctly as described in https://alternerdtive.github.io/VoiceAttack-profiles/installing/#include-profiles?

All these options are working just fin for me.

> How i have my discovery scanner in trigger 2 of the A firegroup it is not working aswell

That is literally the default. Do you have a keyboard bind for secondary fire?

**Comment by suryakumaran11** [comment]
I have fixed the discovery scanner by changing to a keyboard bind instead of the mouse .. 

For the settings .. the voice is not recognizing my accent .. its picking up another word for the "auto" keyword that's why I need to set it manually .. can you please tell me how to do that .. Voice recognition is not very compatible with my country accent. 

EX : If i say "auto honk all system"

it will get it as .. "also change all systems" which is not helping me in any way 

sorry to ask you of this request just for the settings can you tell me how to edit them manually

**Comment by alterNERDtive** [comment]
> I have fixed the discovery scanner by changing to a keyboard bind instead of the mouse ..

As said [in the docs](https://alternerdtive.github.io/VoiceAttack-profiles/installing/#set-elite-keyboard-binds) you will need to set keyboard binds for anything VoiceAttack is supposed to do for you.

> For the settings .. the voice is not recognizing my accent .. its picking up another word for the "auto" keyword that's why I need to set it manually .. can you please tell me how to do that .. Voice recognition is not very compatible with my country accent.

Have you tried using a different voice recognition language? Like, for English there’s a lot of them, US, UK, Indian … there’s also a setting to recognize non-native accents, but I have no idea how effective that is.

You might also want to look at [this thread on the VA forums](https://forum.voiceattack.com/smf/index.php?topic=2667.msg12197#msg12197) regarding voice training and mic setup.

> EX : If i say "auto honk all system"
> 
> it will get it as .. "also change all systems" which is not helping me in any way

The command is “customize setting enable auto honk all systems”, I’ve already linked you [the section of the documentation that covers that](https://alternerdtive.github.io/VoiceAttack-profiles/configuration/general/#settings).

> sorry to ask you of this request just for the settings can you tell me how to edit them manually

You _can_ manually fiddle with the settings (in this case, `EliteAttack.autoHonkAllSystems#`) but I recommend fixing the underlying problem instead. Both because doing this stuff manually might break things, and because you won’t have a lot of fun using VoiceAttack if your recognition is messed up.
